Integrate DVC wrapper library Diff method to gold images processing cmd
Nautilus-Cyberneering/nautilus-librarian pull request #52
Opened 2021-12-24 13:09 UTC by yeraydavidrodriguez

Resolves #46

2021-12-28 10:27 UTC, josecelano requested changes

2021-12-29 18:01 UTC, josecelano approved these changes

2021-12-30 13:47 UTC, yeraydavidrodriguez commented on src/nautilus_librarian/typer/commands/workflows/gold_images_processing.py
> +        poetry run nautilus-librarian gold-images-processing /path/to/repo '{"added":[{"path":"data/000001/32/000001-32.600.2.tif"}],"deleted":[],"modified":[],"renamed":[]}' # noqa
We finally renamed the env vars using alternative n.3

2021-12-30 13:48 UTC, yeraydavidrodriguez commented on src/nautilus_librarian/typer/commands/workflows/gold_images_processing.py
> +    dvc_diff: str = typer.Argument(None, envvar="INPUT_DVC_DIFF"),
We finally have left this argument as a non-mandatory option, as it can be useful in certain scenarios

2021-12-30 14:28 UTC, josecelano approved these changes

2021-12-30 14:31 UTC, merged